### ISSUE TITLE
Add `cancel-stuck-transactions`

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-api#425]
- [x] https://github.com/filecoin-station/spark-evaluate/commit/b30115d460fd65bd2c9a64bb7788488977bb9acf
- [x] https://github.com/filecoin-station/spark-evaluate/commit/cce5c11f97f7e447db63094624d2d8a69cdaafe2
- [x] https://github.com/filecoin-station/spark-evaluate/commit/19da7d98396bd666cbbac515a2ee3001df1e2cbc
- [x] https://github.com/filecoin-station/spark-evaluate/commit/7608ee39db71871061375ab8009a31826e9e6c75
- [x] storage tests

**Comment by bajtos** [comment]
@juliangruber Would you mind adding a test to ensure the `store` implementation works as expected? (See the discussion in https://github.com/filecoin-station/spark-evaluate/pull/368.) Now that this is no longer an urgent fix, I feel more strongly that we should do the extra bit of work to cover `store` by tests. Especially since this code is rarely executed, only when things go wrong, which is the worst time to discover something does not work.
