### ISSUE TITLE
Rework CID list to test HTTP protocol only

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-api#44]
via Will Scott:

to get a list of all HTTP-enabled SPs:
- https://heyfil.prod.cid.contact/sp?status=1 (and status=2,3,…) find known SPs with data
  - the ‘status’ values are https://github.com/ipni/heyfil/blob/main/target.go#L44
- for the sp, https://heyfil.prod.cid.contact/sp/f010088 shows what ‘transports’ (so e.g. https://heyfil.prod.cid.contact/sp/f01889668 has http)

for a given cid:
- https://cid.contact/cid/<cid> shows providers for the cid
- identify SPs as nodes that support both graphsync and http?

via @bajtos:

I can see HTTP endpoints listed on IPNI website, the protocol is described as 0 or 2336.
Example CID (hosted by DAG house, found in spark-api DB): bafybeiezeds576kygarlq672cnjtimbsrspx5b3tr3gct2lhqud6abjgiuz

See also: https://github.com/multiformats/multicodec/blob/master/table.csv

**Comment by bajtos** [comment]
I did most of the necessary work in https://github.com/filecoin-station/spark/issues/12.

We cannot switch to HTTP retrievals only, because for the CIDs in Saturn's TOP1000 CID list, only web3.storage advertises HTTP support.

Let's keep this issue open to remind us to remove non-http retrieval templates once we have a larger data set.

**Comment by bajtos** [comment]
spark-api work is done, spark-checker work continues here:
- https://github.com/filecoin-station/spark/issues/46
